services:
  - type: web
    name: pokemon-tcg-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
